### ISSUE TITLE
pkgfmt(1) should mention format version options

### ISSUE THREAD

**Issue by jclulow** [omniosorg/pkg5#205]
An illumos contributor was recently confused by a message output from our build that asked them to run `pkgfmt` without the `-c` or `-d` options to reformat a manifest file.  Unfortunately it was not immediately obvious that the tool operates by default (it seems) in the V2 format mode, which we don't use in illumos.  You can override the format in use with the `PKGFMT_OUTPUT` environment variable, as the build does, but it seems like there is also an undocumented `-f` flag for this?

It'd be good to document the flag and the environment variable, and likely to specifically call out in the manual page that illumos only uses the V1 output format.

**Comment by citrus-it** [comment]
I wonder if the illumos build should re-iterate that they should do that inside a `bldenv`?
Do you know reason illumos still uses the v1 format?

No objections to updating the man page but maybe we should look at allowing either format in illumos.
