### ISSUE TITLE
Support short cut for `wait` for bhyve and kvm zones `vnc` attribute

### ISSUE THREAD

**Issue by idodeclare** [omniosorg/pkg5#217]
Though you can indicate to wait by setting the `vnc` attribute using full _`options`_ such as `unix=/tmp/vm.vnc,wait`, may I suggest another mode for `vnc`: `off, on, wait,`_`options`_ where `wait` is the same as `unix=/tmp/vm.vnc,wait`.

Thank you.

**Comment by citrus-it** [comment]
Good idea - I've just created a PR to add that for bhyve. It does not work in kvm.

**Comment by idodeclare** [comment]
Thank you!

(I'm hopeful your multiple `cdrom` is released soon too.)
