### ISSUE TITLE
vnc=wait is not documented in bhyve(5)

### ISSUE THREAD

**Issue by idodeclare** [omniosorg/pkg5#353]
I've noticed the bhyve man page and your web site, https://omnios.org/info/bhyve_kvm_brand.html, do not document the `vnc=wait` setting.

**Comment by oetiker** [comment]
the manual pages have their own site ... https://man.omnios.org/man1m/bhyve#wait the page you refere to is simply an introduction ... that said, if you would like to provide updates, we are more than happy for PRs on https://github.com/omniosorg/omniosorg.github.io/blob/master/_docs/info/bhyve_kvm_brand.md

**Comment by idodeclare** [comment]
I mean src/man/bhyve.5 as the first document above.
