### ISSUE TITLE
pkg install could report success if all packages were already installed

### ISSUE THREAD

**Issue by jclulow** [omniosorg/pkg5#394]
It would be good to at least have a flag that would allow for idempotent use of `pkg install blah`, such that if `blah` is already installed and no action is required we can drive on successfully instead of exiting non-zero.  Today, to work around this, folks always have to do something like `pkg info -q blah` to try and guess if the package is installed before putting it in the list.  This is even more tedious if you have a list of multiple packages, as if _some_ of them are not installed we will successfully install the missing ones, but if _all_ of them are installed we fail with the error.

**Comment by citrus-it** [comment]
That sounds like a good idea to simplify things. Note that the error codes are different in those cases so it is possible to distinguish without having to do the `pkg info`, but an option to convert exit status 4 into 0 would be useful.

```
build# pkg install blah

pkg install: The following pattern(s) did not match any allowable packages.  Try
using a different matching pattern, or refreshing publisher information:

        blah
build# echo $?
1
build# pkg install gnu-tar
No updates necessary for this image.
build# echo $?
4
```

**Comment by citrus-it** [comment]
bump
