### ISSUE TITLE
installation in a sparse-zone can 'succeed' when a package has files in a shared filesystem

### ISSUE THREAD

**Issue by mounty1** [omniosorg/pkg5#401]
An example is _isc-dhcp_, which has _/usr/sbin/dhcpd_.  If this package be installed in a sparse zone, then `pkg install` reports no error, but _/usr/sbin/dhcpd_ is not installed because filesystem _/usr_ is shared and read-only in the zone.

At the very least, `pkg install` should emit a warning for the omitted file, but really, `pkg install` should fail because the package has not been installed.

**Comment by mounty1** [comment]
I don't understand the logic of `pkg install` succeeding when _the package has not been installed_.  It seems to me that the warning should apply only in the presence of an enabling command-line flag and that the default action should be to fail.

**Comment by mounty1** [comment]
Concerning the cases above:

1.  If the file is in _/usr_ for example by the package having been installed in the global zone then that counts as installed, provided the file has the same content and ownership.  That's "installed by already being there".
2. If the links aren't necessary, why are they in the package?  That's maybe a case for a file being marked "nice to have" or "not required for successful installation" but that's an unusual case.

If shell scripts are relying on packages being installed when they are not, then the shell scripts are already broken.  That argument gives excessive weight to backward compatibility.

I don't see any point in continuing just to argue this back and forth.  I've said my piece and it's now up to the maintainers of OmniOS to decide what to do with this this issue.

**Comment by citrus-it** [comment]
> If shell scripts are relying on packages being installed when they are not, then the shell scripts are already broken.

I think at this point it's a matter of semantics. The packages are installed, just some of their actions may have been elided due to the image configuration. There was a suggestion posted on the pull request associated with this issue that we introduce a new image property to control the behaviour, which allows flexibility. I've gone ahead and updated the pull request with that. For sparse zones, the default behaviour will be to reject the operations.
